version: "3.4"

services:
  backend:
    build: .

  database:
    image: postgres:11.2-alpine
    restart: always
    volumes:
      - database-data:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgraphile:
    image: graphile/postgraphile
    ports:
      - 5000:5000

volumes:
  database-data:
